version: "3"
services:
  logstash:
    build: .
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_OAUTH_TOKEN
      - TWITTER_OAUTH_TOKEN_SECRET
    volumes:
      - ./data:/usr/share/logstash/scandata
